version: '3'

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: hc_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5777:5432"
    restart: unless-stopped
    networks:
      - bo_network  # Add network

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: hc_postgres_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "5757:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - bo_network  # Add network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  bo_network:  # Define a custom network