name: buildimage-push-docker-repo

on: 
  pull_request:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Latest Tag from Docker Hub
        id: get-latest-tag
        run: |
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/boeingporrapat/hp-frontend/tags/" | jq -r '.results | map(.name) | map(select(test("^v[0-9]+\\.[0-9]+$"))) | sort | last')
          if [[ "$LATEST_TAG" == "null" ]]; then
            NEW_TAG="v1.0"
          else
            MAJOR=$(echo "$LATEST_TAG" | cut -d. -f1 | sed 's/v//')
            MINOR=$(echo "$LATEST_TAG" | cut -d. -f2)
            NEW_TAG="v${MAJOR}.$((MINOR + 1))"
          fi
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "Latest tag: $LATEST_TAG"
          echo "New tag: $NEW_TAG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            boeingporrapat/hp-frontend:${{ env.NEW_TAG }}